name: Builder
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build production website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "15.x"
      - name: Pull main changes to gh-pages branch
        run: |
          git fetch 
          git checkout -d gh-pages
          git push origin main
          git checkout -b gh-pages
      - name: Install npm packages
        run: |
          npm i \
          npm i -g parcel-bundler
      - name: Build Website
        run: parcel build --no-source-maps index.html
      - name: Remove unnecessary files
        run: |
          rm -rf !(dist)
          mv dist/* .
          rmdir dist
      - name: Push built files to gh-pages
        run: |
          git add .
          git commit -m "Web built"
          git push origin gh-pages