name: Builder
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build production website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install Parcel and build
        run: \
          PATH=/opt/hostedtoolcache/node/12.21.0/x64/bin/node:/opt/hostedtoolcache/node/12.21.0/x64/bin/npm:$PATH
          node -v \
          npm i \
          parcel build --no-source-maps index.html