name: Builder
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build production website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "15.x"
      - name: Install npm packages
        run: |
          npm i \
          npm i -g parcel-bundler
      - name: Build Website
        run: parcel build --no-source-maps index.html
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist