name: Builder
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build production website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Parcel and build
        run: \
        curl -fsSL https://deb.nodesource.com/setup_12.x | sudo -E bash - \
        sudo apt-get install -y nodejs \
          node -v \
          npm i \
          parcel build --no-source-maps index.html