name: Builder
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build production website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
